SELECT H.HACKER_ID, H.NAME
FROM SUBMISSIONS AS S
       JOIN
     HACKERS AS H
     ON H.HACKER_ID = S.HACKER_ID
       JOIN
     CHALLENGES AS C
     ON C.CHALLENGE_ID = S.CHALLENGE_ID
       JOIN
     DIFFICULTY AS D
     ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
WHERE
    S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(S.HACKER_ID) > 1
ORDER BY COUNT(S.HACKER_ID) DESC, S.HACKER_ID ASC;